### ISSUE TITLE
[Solved] Failed to install certificate in Cpanel

### ISSUE THREAD

**Issue by Xavron** [neurobin/sslic#2]
For some reason the certificate fails to install by script

Successfully renewed certificate followed by Failed to install certificate in Cpanel

Previously got it to work once by setting cpanel cron job to run right away (eg one to five minutes) and it installed. This time it won't so had to download the dom.crt and manually install it in cpanel.

I'm still not sure what the reason is but there are a few things I can find from the logs and email:

`<b>Warning</b>:  error_log(): It is not safe to rely on the system's timezone settings. You are *required* to use the date.timezone setting or the date_default_timezone_set() function.`

`The CURL call did not return valid JSON`

```
<!-- EXTERNAL CSS -->
<link href="/cPanel_magic_revision_1386192030/unprotected/nc-cpanel/fonts/open_sans/open_sans.min.css" rel="stylesheet" type="text/css" />
<link href="/cPanel_magic_revision_1513675560/unprotected/nc-cpanel/style_v2_optimized.css" rel="stylesheet" type="text/css" />
<style type="text/css">
/* This css is included in the base template in case the css cannot be loaded because of access restrictions
    If this css is updated, please update main.tmpl as well */
```

**Comment by neurobin** [comment]
Try running it with `php-cli` rather than `php`.

**Comment by Xavron** [comment]
Thanks, will reply again as soon as I've tested it

**Comment by Xavron** [comment]
Alright, fixed it. There were two problems in combination.

I had at some point (must have been while really busy) changed the cpanel password very slightly in one password manager but did not change it in another one I use and in the script so thought it was correct when it wasn't.

Finding that one took adding in to sslic.php:

    curl_setopt( $ch, CURLOPT_FAILONERROR, true);
    ...
    if(curl_errno($ch)){
    err('Curl error: ' . curl_error($ch));
    }

And the second problem was (what should also be obvious but only if you are thinking about it) two factor auth which sllic.php is incapable of dealing with which I also enabled without even thinking about the script.

_Suggestion:_ If there's a way to run this script (install the cert) with two factor enabled then it would be good to re-work it accordingly for better security. The password in plain text wouldn't matter nearly as much in that case. Security should be priority today.

_Suggestion:_ It took a while to find the first one because there was no error log for this by default and thought it was the correct password because the one password manager that I use to check it was also the same. Just something to think about that the current error log doesn't help there but instead just says "The CURL call did not return valid JSON" which is completely unhelpful.

**Comment by neurobin** [comment]
Thanks for the suggestions. Your first suggestion has been implemented in the latest version.

**Comment by Xavron** [comment]
That makes a huge difference when it goes wrong and it looks good how you implemented it. Thanks =)
