### ISSUE TITLE
[Solved] 2FA compatibility

### ISSUE THREAD

**Issue by Xavron** [neurobin/sslic#3]
https://documentation.cpanel.net/display/DD/Guide+to+API+Authentication+-+Two-Factor+Authentication

Have you looked into if this will work here for compatibility with 2FA? It looks like the user doesn't need to be around due to the username and pass being in the script so I would expect it to work but its the first time I've ever looked at the cpanel API so not familiar with it.

When I have some time to spend on it, could play around with it and check it out. You're welcome to get to it first or maybe you've already tried it.

**Comment by neurobin** [comment]
No, I currently don't have much time to check it out. Maybe in future...

**Comment by Xavron** [comment]
Ok, I will look into it asap and reply when there's something =)

**Comment by neurobin** [comment]
doesn't this 2FA require manual intervention? If so, then it won't be of much use here.

**Comment by Xavron** [comment]
> doesn't this 2FA require manual intervention? If so, then it won't be of much use here.

Yeah, that's what I was wondering. They show the username and password in plain text but maybe the secret can't be.

I will keep looking. There has to be something or their API breaks when user enables 2FA which is horrible.

**Comment by Xavron** [comment]
Spent some time on this today, and at least at this time, I can still find nothing that will work correctly.

The link I listed above does show https://github.com/lelag/otphp as being used which does need user presence and maybe not good here anyway as the OTP generated is through cpanel's 2fa enable barcode and not from this one here. A workaround or bad hack may decrease security.

Guessing that is the current downside to enabling 2fa, that no one has cared to implement something where all the same things can be done, while maintaining the better security.

Will leave this open because its unresolved but you can close it if you feel its not resolvable.

**Comment by Xavron** [comment]
Going a different way. Found out that it should be possible to install via cron job sh script which is technically better.

(edit: that is direct via command line)

Almost have it working. Have one minor issue to work out right now then should know if it definitely works.

**Comment by Xavron** [comment]
And have it working... Will clean up the script and post all the details asap.

Edit - Well that had a negative effect haha. Need to figure out namecheap python so it doesn't break things and then its solved.

**Comment by Xavron** [comment]
https://gist.github.com/Xavron/8ced1441fc48a6937e5a711a20c55854

You can do with this as you please. As far as I'm concerned this is solved ;-)

**Comment by Xavron** [comment]
Additional info: Looks like that allows your sslic to be removed (at least for me at this time - you can re-work sslic should you want) and even the ~~username and~~ password to be removed as its no longer in use yes? That increases security even further.

~~(I have yet to test this but at a glance it seems to be correct as the only use of the varibles seems to be for sslic account login.)~~

Automatic test without password in script (along with my attached script) ran successfully with new cert created and installed. 2FA enabled :-D
